Repository animores/animores-server, pull requests merged in 2024-05, with the labels that each got.

#67 Swagger update
  .github/workflows/cd.yml
  build.gradle
  src/main/java/animores/serverapi/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: documentation

#66 Error Handling 추가
  build.gradle
  src/main/java/animores/serverapi/account/controller/AccountController.java
  src/main/java/animores/serverapi/account/service/impl/GoogleEmailAuthServiceImpl.java
  src/main/java/animores/serverapi/common/exception/GlobalExceptionHandler.java
  src/main/java/animores/serverapi/pet/controller/PetController.java
  src/main/java/animores/serverapi/pet/entity/Breed.java
  src/main/java/animores/serverapi/pet/entity/BreedImage.java
  src/main/java/animores/serverapi/pet/entity/Pet.java
  src/main/java/animores/serverapi/pet/entity/Species.java
  src/main/java/animores/serverapi/pet/repository/PetRepository.java
  src/main/java/animores/serverapi/pet/service/PetService.java
  src/main/java/animores/serverapi/pet/service/impl/PetServiceImpl.java
  src/main/java/animores/serverapi/to_do/entity/PetToDoRelationship.java
  src/main/java/animores/serverapi/to_do/service/impl/ToDoServiceImpl.java
  src/test/java/animores/serverapi/account/service/impl/GoogleEmailAuthServiceImplTest.java
  src/test/java/animores/serverapi/to_do/service/impl/ToDoServiceImplTest.java
Labels: enhancement

#70 To Do Request Context 적용 / Page Response 적용 / Swagger update
  src/main/java/animores/serverapi/account/controller/AccountController.java
  src/main/java/animores/serverapi/common/aop/UserInfo.java
  src/main/java/animores/serverapi/common/aop/UserInfoAspect.java
  src/main/java/animores/serverapi/common/exception/ExceptionCode.java
  src/main/java/animores/serverapi/config/SwaggerConfig.java
  src/main/java/animores/serverapi/pet/service/PetService.java
  src/main/java/animores/serverapi/pet/service/PetServiceImpl.java
  src/main/java/animores/serverapi/to_do/controller/ToDoController.java
  src/main/java/animores/serverapi/to_do/dao/GetToDoPageDao.java
  src/main/java/animores/serverapi/to_do/dao/ToDoDao.java
  src/main/java/animores/serverapi/to_do/dao/ToDoInstanceDao.java
  src/main/java/animores/serverapi/to_do/dto/request/ToDoCreateRequest.java
  src/main/java/animores/serverapi/to_do/dto/request/ToDoPatchRequest.java
  src/main/java/animores/serverapi/to_do/dto/response/ToDoPageResponse.java
  src/main/java/animores/serverapi/to_do/dto/response/ToDoResponse.java
  src/main/java/animores/serverapi/to_do/repository/PetToDoRelationshipRepository.java
  src/main/java/animores/serverapi/to_do/repository/ToDoInstanceCustomRepository.java
  src/main/java/animores/serverapi/to_do/repository/impl/ToDoInstanceCustomRepositoryImpl.java
  src/main/java/animores/serverapi/to_do/service/ToDoService.java
  src/main/java/animores/serverapi/to_do/service/impl/ToDoServiceImpl.java
  src/test/java/animores/serverapi/to_do/service/impl/ToDoServiceImplTest.java
Labels: documentation, enhancement

#73 Pet api 구현
  src/main/java/animores/serverapi/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/animores/serverapi/diary/controller/DiaryController.java
  src/main/java/animores/serverapi/pet/controller/PetController.java
  src/main/java/animores/serverapi/pet/dao/PetDao.java
  src/main/java/animores/serverapi/pet/dto/PetDto.java
  src/main/java/animores/serverapi/pet/dto/request/PetCreateRequest.java
  src/main/java/animores/serverapi/pet/dto/response/BreedResponse.java
  src/main/java/animores/serverapi/pet/dto/response/GetPetDetailResponse.java
  src/main/java/animores/serverapi/pet/dto/response/PetCreateResponse.java
  src/main/java/animores/serverapi/pet/dto/response/SpeciesResponse.java
  src/main/java/animores/serverapi/pet/entity/Pet.java
  src/main/java/animores/serverapi/pet/repository/BreedRepository.java
  src/main/java/animores/serverapi/pet/repository/PetCustomRepository.java
  src/main/java/animores/serverapi/pet/repository/PetRepository.java
  src/main/java/animores/serverapi/pet/repository/SpeciesRepository.java
  src/main/java/animores/serverapi/pet/repository/impl/PetCustomRepositoryImpl.java
  src/main/java/animores/serverapi/pet/service/PetService.java
  src/main/java/animores/serverapi/pet/service/impl/PetServiceImpl.java
  src/test/java/animores/serverapi/pet/service/impl/PetServiceImplTest.java
  src/test/java/animores/serverapi/to_do/service/impl/ToDoServiceImplTest.java
Labels: enhancement

#60 일지 관심 api 구현
  src/main/java/animores/serverapi/common/exception/ExceptionCode.java
  src/main/java/animores/serverapi/diary/controller/DiaryWishController.java
  src/main/java/animores/serverapi/diary/dto/AddDiaryWishRequest.java
  src/main/java/animores/serverapi/diary/dto/CancelDiaryWishRequest.java
  src/main/java/animores/serverapi/diary/entity/DiaryWish.java
  src/main/java/animores/serverapi/diary/repository/DiaryWishRepository.java
  src/main/java/animores/serverapi/diary/service/DiaryWishService.java
  src/main/java/animores/serverapi/diary/service/impl/DiaryWishServiceImpl.java
Labels: enhancement

#75 account Auth 수정 및 Swagger 설명 추가
  src/main/java/animores/serverapi/account/controller/AccountController.java
  src/main/java/animores/serverapi/account/request/SignInRequest.java
  src/main/java/animores/serverapi/account/request/SignOutRequest.java
  src/main/java/animores/serverapi/account/request/SignUpRequest.java
  src/main/java/animores/serverapi/account/service/AccountService.java
  src/main/java/animores/serverapi/account/service/EmailAuthService.java
  src/main/java/animores/serverapi/account/service/impl/AccountServiceImpl.java
  src/main/java/animores/serverapi/account/service/impl/GoogleEmailAuthServiceImpl.java
  src/main/java/animores/serverapi/common/exception/ExceptionCode.java
  src/main/java/animores/serverapi/security/RefreshRequest.java
  src/main/java/animores/serverapi/security/TokenProvider.java
  src/test/java/animores/serverapi/account/service/impl/AccountServiceImplTest.java
Labels: enhancement

#78 diary 삭제 api 구현 및 기타 코드 수정
  src/main/java/animores/serverapi/diary/controller/DiaryController.java
  src/main/java/animores/serverapi/diary/dto/RemoveDiaryRequest.java
  src/main/java/animores/serverapi/diary/repository/impl/DiaryCustomRepositoryImpl.java
  src/main/java/animores/serverapi/diary/service/DiaryService.java
  src/main/java/animores/serverapi/diary/service/impl/DiaryServiceImpl.java
Labels: enhancement

#81 multipart 관련 오류 수정
  src/main/java/animores/serverapi/diary/controller/DiaryController.java
Labels: bug

#84 로그인 무력화
  src/main/java/animores/serverapi/common/aop/UserInfoAspect.java
  src/main/java/animores/serverapi/diary/controller/DiaryController.java
  src/main/java/animores/serverapi/pet/controller/PetController.java
  src/main/java/animores/serverapi/security/SecurityConfig.java
Labels: enhancement
